service: to-do-application-backend-api
frameworkVersion: '2'

provider:
  name: aws
  runtime: java8
  lambdaHashingVersion: 20201221
  region: eu-west-2
  profile: serverless
  apiGateway:
    shouldStartNameWithService: true

package:
  artifact: target/hello-dev.jar

functions:
  tasks-api:
    handler: com.techreturners.Handler
    events:
#      - httpApi:
      - http:
          path: tasks
          method: get