service: to-do-application-backend-api
frameworkVersion: '2'

provider:
  name: aws
  runtime: java8
  lambdaHashingVersion: 20201221
  region: eu-west-2
  profile: serverless
  apiGateway:
    shouldStartNameWithService: true

package:
  artifact: target/tasks-java-api-dev.jar

functions:
  get-tasks-java-api:
    handler: com.techreturners.GetTasksHandler
    events:
      - http:
          path: /users/{userId}/tasks
          method: get