service: to-do-application-backend-api
frameworkVersion: '2'

provider:
  name: aws
  runtime: java8
  lambdaHashingVersion: 20201221
  region: eu-west-2
  profile: serverless
  apiGateway:
    shouldStartNameWithService: true
  environment:
    DB_HOST: ${file(./config.dev.json):DB_HOST}
    DB_NAME: ${file(./config.dev.json):DB_NAME}
    DB_USER: ${file(./config.dev.json):DB_USER}
    DB_PASSWORD: ${file(./config.dev.json):DB_PASSWORD}

package:
  artifact: target/tasks-java-api-dev.jar

functions:
  get-tasks-java-api:
    handler: com.techreturners.GetTasksHandler
    events:
      - http:
          path: /users/{userId}/tasks
          method: get
  save-tasks-java-api:
    handler: com.techreturners.SaveTasksHandler
    events:
      - http:
          path: /users/{userId}/tasks
          method: post